### PR TITLE
Fixes #338 - Also cache fonts registered through fontconfig

### LINKED ISSUE #338: Unexpected delay in embedding svg to pdf while upgrading svglib to 1.2.1
I am currently using svglib 0.9.0 and reportlab to create pdf reports from svg images and other information. While I wanted to upgrade to the latest version of svglib 1.2.1, I notice that the creation of reports in the latest version is much slower than in the older version. This has greatly impacted the overall performance. Can anyone assist me with this issue?

The minimal code for testing is provided below:

```
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Table
from reportlab.lib.pagesizes import A4
from svglib.svglib import svg2rlg
import time

def page_body(w, h):
    image_path = <PATH_TO_SVG>
    drawing = svg2rlg(image_path)
    res = Table([[drawing]], w, h)
    res.setStyle(
        [
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    )
    return res

def create_report():
    startTime = time.time()
    canvas = Canvas("page.pdf", pagesize=A4)
    canvas.setTitle("SVG Example")
    # table
    width, height = A4
    page = Table(
        [
            [
                "",
                page_body(width - 2 * 50, 0.78 * height),
                "",
            ]
        ],
        colWidths=[50, (width - 2 * 50), 50],
        rowHeights=[0.78 * height],
    )
    page.setStyle(
        [
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ]
    )
    page.wrapOn(canvas, 0, 0)
    page.drawOn(canvas, 0, 0)
    canvas.showPage()
    canvas.save()
    print("Time taken =", time.time() - startTime)

```

**Environment:**

Ubuntu
Python 3.9
reportlab==3.6.9

**Test run output:**

_svglib 0.9.0_  Time taken = 0.05732107162475586
_svglib 0.9.3_  Time taken = 0.06111264228820801
_svglib 1.1.0_  Time taken = 2.747704267501831
_svglib 1.2.1_  Time taken = 2.7683348655700684

### PR DESCRIPTION
**Pull request by claudep**
Fixes a performance regression in 83d2ec043e094562f.

### CODE REVIEW

**Comment by karlb** [comment]
This does not resolve the performance regression for me. Here's a profile of my (admittedly far from minimal) case using this branch:

```
Sat May 14 08:28:24 2022    pdfgen.prof

         68571541 function calls (60673417 primitive calls) in 417.654 seconds

   Ordered by: internal time
   List reduced from 9286 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    60067  254.892    0.004  254.892    0.004 {method 'poll' of 'select.poll' objects}
    90093   50.078    0.001   50.078    0.001 {built-in method posix.read}
    15016   41.077    0.003   41.077    0.003 {built-in method _posixsubprocess.fork_exec}
791892/261374    2.729    0.000    3.625    0.000 svglib.py:173(findAttr)
   849194    2.345    0.000    2.345    0.000 {built-in method posix.stat}
    15016    2.032    0.000   98.412    0.007 subprocess.py:1663(_execute_child)
    21532    1.838    0.000  197.603    0.009 svglib.py:1342(applyStyleOnShape)
   626738    1.786    0.000    3.845    0.000 attrmap.py:99(validateSetattr)
  1008191    1.524    0.000    2.459    0.000 posixpath.py:71(join)
    30044    1.521    0.000    9.022    0.000 ttfonts.py:145(TTFOpenFile)
    15016    1.356    0.000  260.523    0.017 subprocess.py:1928(_communicate)
8244450/8244430    1.351    0.000    1.456    0.000 {built-in method builtins.isinstance}
6250695/520643    1.261    0.000    1.434    0.000 basic.py:2028(_preorder_traversal)
3406254/3406189    1.165    0.000    1.253    0.000 {built-in method builtins.getattr}
     7504    1.014    0.000  385.925    0.051 svglib.py:1038(convertText)
   219409    1.013    0.000    1.013    0.000 {method 'split' of 'str' objects}
    15016    0.987    0.000    2.823    0.000 subprocess.py:1207(_close_pipe_fds)
    60729    0.921    0.000    0.923    0.000 {built-in method io.open}
    15016    0.878    0.000  365.387    0.024 fonts.py:77(use_fontconfig)
   362903    0.826    0.000    0.826    0.000 {built-in method reportlab.lib._rl_accel.fp_str}
```
[pdfgen.prof.zip](https://github.com/deeplook/svglib/files/8692374/pdfgen.prof.zip)

Do I have to use svglib in a specific way to take advantage of the caching?

**Comment by claudep** [comment]
Ah yes, sorry. I see my patch does improve things for unknown fonts, but in this case, there is another branching scenario where registering the font fails with a `TTFError`. I'll work on improving this.

**Comment by claudep** [comment]
Could you please test the result now?

**Comment by karlb** [comment]
Works for me now. This makes a 20x speed difference in my case. Thanks fixing it so quickly!

**Comment by Holger-Bartel** [comment]
Thanks a lot @claudep for fixing that one and to @salistha-shakya and @karlb for reporting it!

**Pull request merged**
