### PR TITLE
Remove Python2 numerical relics and fix % formatting in logging

### PR DESCRIPTION
**Pull request by eumiro**

### CODE REVIEW

**Comment by deeplook** [comment]
Thanks! LGTM! Just nosey, did you run a tool for spotting the ints/floats? If so which one?

**Comment by eumiro** [comment]
I just sought for `int`, `float`, looked at the literal numerals and watched my GeoPython 2021 talk :-)

Looks like you'll need to set the environment for Python 3.9 in AppVeyor to run it correctly. See https://www.appveyor.com/docs/windows-images-software/#python for different Visual Studio versions.

**Review by claudep — APPROVED** [review]
Thanks, looks good!

**Comment by deeplook** [comment]
Frankly, I don't see how to add a py39 environment for AppVeyor: https://ci.appveyor.com/project/deeplook/svglib. Maybe it's time to move to https://docs.github.com/en/actions/guides/building-and-testing-python?

**Comment by eumiro** [comment]
> Frankly, I don't see how to add a py39 environment for AppVeyor: https://ci.appveyor.com/project/deeplook/svglib. Maybe it's time to move to https://docs.github.com/en/actions/guides/building-and-testing-python?

Right, let's do it in #271

**Comment by eumiro** [comment]
Rebased onto GHA/Travis/Appveyor changes, so the Python versions migration touches PyPI classifiers only. The removal of Python2 int/float relics and proper `%` log formatting have not been touched.

**Comment by deeplook** [comment]
I have now deleted this project from https://ci.appveyor.com/account/deeplook/projects.

**Pull request merged**
