### PR TITLE
Replaced prints by logging calls

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Please review carefully the logging levels (error/warn/debug), as I was not always sure of my choices!

**Comment by deeplook** [comment]
The `unusedAttrs` stuff was meant to track features of the SVG which were not (yet) handled. There is surely a better way of doing it, but I'd like to keep the idea around.

**Comment by claudep** [comment]
Well... did I remove that?

**Comment by deeplook** [comment]
In fact, not. I hadn't read the entire commit.

**Pull request merged**
