### PR TITLE
WIP: Release svglib 0.9.1

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@deeplook After #189 is merged, it would be nice to release a new version on Pypi.

**Comment by deeplook** [comment]
@claudep I agree. Would you mind adding yourself as author? More than deserved... ;) I'm also open to create a new shared account at PyPI and transfer this code from to it (I think that's possible), in order to have higher flexibility for releases.

**Comment by deeplook** [comment]
BTW, do we care about AppVeyor errors? I mean it would not be nice to see a "broken build" badge on PyPI...

**Comment by claudep** [comment]
I think the author field in setup.py does not support well multiple authors, so I'm fine keeping you as author (unless you plan to completely stop working on svglib). On PyPI, I think you can easily add other persons as co-maintainers, my username is also claudep.

I'm sorry about AppVeyor errors, however I don't care *at all* for the Windows world. Of course I don't mind if a Windows user comes and fixes those errors, otherwise I won't spend any time on that. We can open a ticket and remove the build in the mean time if you don't want the failing build badge.

**Comment by deeplook** [comment]
@claudep Ok, just made you a maintainer on PyPI. Maybe I'll chase later who kickstarted the Windows build check, as I will defeinitely not do anything about that myself.

**Comment by claudep** [comment]
0.9.1 is online: https://pypi.org/project/svglib

**Comment by deeplook** [comment]
Cool, thanks!!

**Pull request merged**
