### PR TITLE
Initial work on child-node SVG rendering 

### PR DESCRIPTION
**Pull request by jdgwf**
This should be some initial work on #124

### CODE REVIEW

**Comment by claudep** [comment]
Just tell us when it's ready for review.

**Comment by jdgwf** [comment]
Should be good to test :)

**Comment by jdgwf** [comment]
I'm hoping this help/works for you as well. It's working for my project, but I'm not sure I'll be using this library. I'm still tempted to rewrite my flask app that I was gearing this library for to nodejs. Let me know if there's anything else I can do to help :) <3 

Love this work, guys!

**Comment by claudep** [comment]
I reworked a bit your pull request in #126. The result on the test suite `Flag_of_Slovenia.svg` file is still not perfect, but it's already a welcome improvement!

**Comment by jdgwf** [comment]
That's awesome. I also modified the README for 
`renderPM.drawToFile(drawing, "file.png")`
to read
`renderPM.drawToFile(drawing, "file.png", fmt="PNG")` 
because drawToFile (at least the version I have when I was testing) defaults the format as GIF and the resulting file.png is unreadable by most viewers trying to view it as a PNG.
It's a picky thing, but I like good current docs. :)

What's the ETA for this version to show up in the pip(3) repos?

**Comment by claudep** [comment]
Thanks, pushed the README update in 5ee8c5f689ba.
I cannot tell about the release ETA as I'm not a releaser for svglib.

**Comment by deeplook** [comment]
👍 @jdgwf Thanks for moving this forward! Please don't be shy and add yourself to the contributors list, too. 😉 

I'm trying to come-up with some defined release procedure and collected a few good examples to reuse some ideas from: https://github.com/deeplook/svglib/wiki/Release-Process, but it can still take a little while.

**Comment by jdgwf** [comment]
Thanks! It looks like I already am according to GitHub :)

**Pull request closed without merging**
