### PR TITLE
introduce svg2pdf.1 man page

### PR DESCRIPTION
**Pull request by MicroJoe**
It is always nice to have a man page for executables.

### CODE REVIEW

**Review by claudep — APPROVED** [review]
Nice, thanks!

**Comment by deeplook** [comment]
Yay! How do we install this with pip/conda?

**Comment by MicroJoe** [comment]
> Yay! How do we install this with pip/conda?

Added a new commit for `setup.py` to automatically install the man page on the system.

**Comment by deeplook** [comment]
I don't know how much sense it would make to add a test for this, maybe like below? @claudep?

```python
import sys
import subprocess

import pytest

@pytest.mark.skipif(sys.platform.startswith("win"), reason="Man pages not available on Windows.")
def test_installed_manpage():
    """Test if svg2pdf man page was installed."""
    try:
        subprocess.check_output(["man", "svg2pdf"])
        assert True
    except subprocess.CalledProcessError:
        assert False
```

**Comment by MicroJoe** [comment]
I think it does not make sense to test this. You want to be able to run all of the tests before installing the package, but this test would verify that the manpage is installed *after* the package is installed. So it would always fail because tests should be ran before installing the package. In the end I think this kind of test is not necessary. You want to test the code, not the installation process.

My two cents.

**Comment by claudep** [comment]
I can live without a test for that.

**Comment by deeplook** [comment]
I guess you're right. ;)

**Pull request merged**
