### PR TITLE
Fix Python 3 compatibility issues

### PR DESCRIPTION
**Pull request by bayangan1991**

### CODE REVIEW

**Comment by claudep** [comment]
Thanks for the suggestion, but you must be using an old version of svglib, as the `xrange` and `STRING_TYPES` symbols are no longer in use in the most recent svglib code.

**Comment by bayangan1991** [comment]
Ok thanks. I installed straight from pip though. Could that version be updated?

**Comment by claudep** [comment]
There is a beta version available, try installing it with `pip install --pre ...`.

**Comment by bayangan1991** [comment]
Thank you!

**Pull request closed without merging**
