### PR TITLE
Release 1.1.0

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@deeplook Are you OK with the 1.1.0 numbering for this release?

**Comment by deeplook** [comment]
@claudep Of course! One might want to add recent contributors to CONTRIBUTORS.rst if they want, or do it later after compiling the list.

I'm curious how downloads will continue to grow with the next release, and I still don't see a good explanation for the recent growth. Maybe a "pandemic effect"? ;) https://pepy.tech/project/svglib

**Comment by claudep** [comment]
Surely, contributors should feel free to add themselves to CONTRIBUTORS file.

Interesting stats, indeed!

**Comment by deeplook** [comment]
@claudep Thank you for making the release!

**Pull request merged**
