### PR TITLE
Exclude a W3C SVG test file that freezes svglib

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
Of course, it would be better to debug the issue, but I don't have the time right now.

**Comment by claudep** [comment]
@deeplook How much effort should we continue to put on the Python 2 version? Just to know if it's worth taking the time to fix the Python 2 test failure.

**Comment by deeplook** [comment]
My gut feeling would be to support Python 2 as long as it is supported itself, but it would be ok to simply skip one test for this version using pytest's skip feature, and maybe revisit it later.

**Comment by claudep** [comment]
Whoo-hoo!

**Comment by deeplook** [comment]
Nice! Thanks! 💯

**Pull request merged**
