### PR TITLE
Refs #343 - Don't forget to render tail of text nodes

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
The patch may need some more work.

**Comment by claudep** [comment]
@jspobst, if you want to test this PR, you are welcome!

**Comment by jspobst** [comment]
I just checked it out, and tested the example code I put in the issue. I can confirm that all of the text shows, but the formatting (ie, italics and bold) still doesn't work. The result: 
image

If this PR was meant only to address some of the text missing before, I'd say it looks good (but doesn't fully close the corresponding issue). Admittedly, I might not understand all of what goes into 'testing this PR', so if that's more than simply generating one pdf, further testing by someone who understands best practices might be needed.

**Comment by claudep** [comment]
I thought you might have other real SVGs that you might test.

The style issue is a completely different thing. svglib doesn't yet support the shorthand `font`, but only the more specific `font-*` properties.

**Pull request merged**
