### PR TITLE
make xlink_href_target method create PIL image instead of temporary file

### PR DESCRIPTION
**Pull request by wgundamj44**
Described in https://github.com/deeplook/svglib/issues/393

The current implementation creates a temporary file and pass its path all the way down to reportlab for render.
It's hard to find a place to unlink the temporary file because it might be outside of svglib's reach when reportlab is done with the file.

This PR tries to pass PIL Image to reportlab, since reportlab seems to support both file path and Image.

### CODE REVIEW

**Comment by deeplook** [comment]
Thanks! Could you also please add a test case?

**Comment by claudep** [comment]
I think that part of the code is already covered by `test_samples.TestOtherFiles.test_png_in_svg`. @deeplook, did you have another test in mind?

**Comment by deeplook** [comment]
@claudep True, that should do it! Fine then with me.

**Review by claudep — APPROVED** [review]
Thanks, I checked the test suite passes locally on Linux.

**Pull request merged**
