### PR TITLE
Render symbol definitions

### LINKED ISSUE #76: Symbol definitions are not rendered

### PR DESCRIPTION
**Pull request by claudep**
Fixes #76.

### CODE REVIEW

**Comment by claudep** [comment]
Thanks for merging quickly. What about a 0.8.1 release now?

**Comment by deeplook** [comment]
Happy to do that. But might be during next week. Would it make sense to add a simple canned SVG file as an example for what can be rendered now?

**Comment by claudep** [comment]
Could be. Do you mean something different than the sample files from the tests?

**Comment by deeplook** [comment]
Well, maybe we could add the Asturia score if there are no copyright issues? But I kind of doubt it. Maybe @Mygod knows?

**Comment by Mygod** [comment]
I suggest not to.

**Pull request merged**
