### PR TITLE
Update svglib.py

### PR DESCRIPTION
**Pull request by skidzo**
line 747, in convertPath'
for i in xrange(0, len(normPath), 2):', "NameError: name 'xrange' is not defined"

### CODE REVIEW

**Comment by claudep** [comment]
Thanks but this was already fixed in 6eb609f.

**Comment by claudep** [comment]
@deeplook we really need a release :-)

**Comment by deeplook** [comment]
@claudep I know, I know. I put some hope on https://github.com/deeplook/svglib/issues/140, which might be the fastest solution...

**Comment by claudep** [comment]
Well, isn't a release essentially running two commands?:
`python setup.py sdist`
`twine upload dist/svglib-x.y.z.tar.gz`

**Comment by deeplook** [comment]
@claudep There are files to synchronize manually with the latest version number (at least the README), and much output from the test suite that is actually not "tested", but ideally needs to be "eye-balled". This has taken me considerable time in the past. But I'm willing to spend parts of the weekend to come on making (and releasing) 0.9.0b (and ignore some quality concerns) which should serve as a point of departure for fixing some of the remaining issues in 0.9.0 one or two weeks later (I won't be able to do much on that myself). When that happens I think it would be ok to nuke 0.9.0b from PyPI, again (showing an appropriate warning in the README). Thoughts?

**Comment by claudep** [comment]
Ah, of course, manually checking rendered files take time. Hopefully regressions should be limited, as we have a bit more tests now. Your plan sounds good.

**Comment by skidzo** [comment]
good luck with the release and the weekend ;-)

**Pull request closed without merging**
