### PR TITLE
CI-based deployment

### PR DESCRIPTION
**Pull request by Overdrivr**
For #140

### CODE REVIEW

**Comment by claudep** [comment]
I would be reluctant to make the release from Windows, but @deeplook will have the final word.

**Comment by Overdrivr** [comment]
It's still WIP, when I'm done the first appveyor job will wait for all
other appveyor jobs and travis jobs, and if everthing is green it will
perform the upload. Since svglib is pure-python, building the package
generates universal wheels, therefore the os does not matter.

**Comment by deeplook** [comment]
@Overdrivr Sorry, I can comment on this only now! Thanks for your efforts, so far! As we have officially added Windows support (to some degree) only very recently, and most people actively hatching this project are likely unable to _really_ support this platform: yes, I would very much like to see deployments triggered by Travis rather than Appveyor.

**Comment by Overdrivr** [comment]
That's fine for me, let me check if I can find some script to tell a travis job to wait for all others + appveyor jobs

**Comment by deeplook** [comment]
This pull request **introduces 1 alert** when merging 1db7eb88ac9fa59d98c5c48081c0c4c3cccf74ca into 137bb3d349364d3c352842dccfb0574b7b2151a0 - [view on LGTM.com](https://lgtm.com/projects/g/deeplook/svglib/rev/pr-793487973d131141d863673102d5392079c325f7)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by deeplook** [comment]
This pull request **introduces 1 alert** when merging af43ff60a76df2973ad42f7aad04f9e88487bafe into 137bb3d349364d3c352842dccfb0574b7b2151a0 - [view on LGTM.com](https://lgtm.com/projects/g/deeplook/svglib/rev/pr-0ca9b5a79795faa714bcca38411674a9c9a8b0c8)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by Overdrivr** [comment]
@deeplook I've made some progress on the CI automation. Here is how it works:

- The first travis job waits for the appveyor build to be either `success` or `failure`. In case of success, it returns with exit code 0, in case of failure it raises an exception

Some remaining stuff to do:
- Make the travis job also check other travis jobs. If all successfull, proceed.
- Interrupt all travis job that are not `XX.1` after the test phase
- Proceed to deployment only if a release tag is found

To enable this workflow, all you will have to do is setup the following environment variables in Travis CI:
- `APPVEYOR_AUTH_TOKEN`
- `APPVEYOR_USER`

The synchronisation logic is written in python. This is an example of what gets displayed during sync:

```
$ python travis_wait_for_appveyor.py
Searching lastest build for commit SHA af43ff60a76df2973ad42f7aad04f9e88487bafe in appveyor project svglib
Syncing with Appveyor build 1.0.2
Appveyor build status: running
Retrying in 60 secs
Syncing with Appveyor build 1.0.2
Build has finished with 2018-09-19T12:37:18.4916263+00:00
```

Does this sound good to you ?

**Comment by deeplook** [comment]
@Overdrivr Thanks for your efforts. Sounds like there are some bits left to be done. Ideally, I guess this should be tested on some other repo/project. Is this part of your efforts? I have not so much time again, for conducting much testing, but this procedure could become interesting for versions >= 1.0 to come.

**Comment by Overdrivr** [comment]
I'm testing those scripts on my own fork of this repo, I'll make sure it works reliably which should not be too hard. This is the kind of stuff that I do on a daily basis at @cronobo and it's a huge time saver. I'll try to finish this in a short while

**Comment by claudep** [comment]
Unfortunately, most of this patch is now outdated, as we use now GitHub actions as CI bot. Thanks anyway for your efforts!

**Pull request closed without merging**
