### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by eumiro**

### CODE REVIEW

**Comment by eumiro** [comment]
The results of this CI run can be seen at https://github.com/eumiro/svglib/actions/runs/534986905

**Review by claudep — APPROVED** [review]
Great, thanks a lot!

**Comment by claudep** [comment]
Could you follow up by removing travis and appveyor configs, please?

**Comment by deeplook** [comment]
@eumiro Bonega! Multan dankon! 💯 👍

**Comment by deeplook** [comment]
Any idea when the CI badge in the README will turn green? ;)

**Comment by eumiro** [comment]
As soon as it ignores appveyor.

**Pull request merged**
