### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by asears**
Fix broken link to reportlab

### CODE REVIEW

**Comment by deeplook** [comment]
@replabrobin Can you confirm that http://reportlab.org is gone forever?

**Comment by deeplook** [comment]
@replabrobin I can see there is content under reportlab.org, although it's not quite what I'd expect. 😉

**Comment by deeplook** [comment]
@replabrobin I can see there is content under reportlab.org, although it's not quite what I'd expect. 😉 Can you elaborate?

**Comment by claudep** [comment]
If the domain name is lost and taken by another entity, I guess this patch should be committed ASAP.

**Review by claudep — APPROVED** [review]

**Pull request merged**
