### PR TITLE
Fix "Prefer `format()` over string interpolation operator" issue

### PR DESCRIPTION
**Pull request by deeplook**
This pull request automatically fixes all occurrences of the following issue:

Issue type: [Prefer `format()` over string interpolation operator](https://www.quantifiedcode.com/app/issue_class/4ACGxFj1)
Issue details: [https://www.quantifiedcode.com/app/project/gh:deeplook:svglib?groups=code_patterns/%3A4ACGxFj1](https://www.quantifiedcode.com/app/project/gh:deeplook:svglib?groups=code_patterns/%3A4ACGxFj1)

To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.

Legal note: We won't claim any copyrights on the code changes.

Cheers,
[Cody - Your code quality bot](https://www.quantifiedcode.com/cody)

### CODE REVIEW

**Comment by claudep** [comment]
We've discussed that issue in the Django project, and didn't opt for the `format` syntax in all cases. The legacy placeholder syntax is not deprecated and is fine for many use cases.

**Comment by deeplook** [comment]
Same for me. But it's a case where the QC bot can easily create a PR himself. ;-)

**Comment by claudep** [comment]
Is it possible to "whitelist" some issues on QC so they are not reported?

**Comment by deeplook** [comment]
Yes, I'm just not sure yet, it's doable only globally or also for individual projects. Will find out. But again, the future of QC is uncertain. I just ran it on svglib in order to do it before the end of 2016.

**Comment by deeplook** [comment]
Closing this here since there is no strict necessity or advantage of moving to `.format()` notation everywhere. This doesn't mean it might not be revisited later.

**Pull request closed without merging**
