### PR TITLE
Proper handling of percentage attributes

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
This should fix the Chinese flag rendering issue.

**Comment by deeplook** [comment]
This pull request **introduces 1 alert** when merging 5f665c2b6b26c14e887cee27d79635cea610a784 into 859f9f461f1041018af3e6f507bb4c0616b04fbb - [view on LGTM.com](https://lgtm.com/projects/g/deeplook/svglib/rev/pr-b860b1dae06dd6f969eeebaeec6095dd9a6da153)

**new alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by claudep** [comment]
Just added the test mentioned in #190

**Comment by claudep** [comment]
Merged manually.

**Pull request closed without merging**
